/**
 * Unit tests for seedDefaultQuestions' platform-org scoping.
 *
 * Generated by /ship coverage audit.
 * Value: protects=with no platform org, signup copies no questions and
 * reports 0; fails_when=the template read loses its platform-org guard (e.g.
 * findMany with orgId undefined, which Prisma treats as no filter) and copies
 * any org's template-flagged rows; why_new=the integration suite cannot remove
 * the shared dev DB's platform org safely; seam=none (seedDefaultQuestions
 * already takes a transaction client from createOrg)
 */

import { describe, expect, it, vi } from 'vitest';

vi.mock('./prisma', () => ({ prisma: {} }));

import { seedDefaultQuestions } from './screenerQuestionsRepo';

describe('seedDefaultQuestions', () => {
	it('copies nothing and returns 0 when there is no platform org', async () => {
		const create = vi.fn();
		// A template-flagged row on some other org: an unscoped read finds it.
		const findMany = vi.fn(async () => [
			{
				key: 'stray',
				prompt: 'Not a platform template',
				type: 'TEXT',
				order: 1,
				configJson: {},
			},
		]);
		const db = {
			organization: { findUnique: vi.fn(async () => null) },
			screenerQuestion: { findMany, create },
		};

		const copied = await seedDefaultQuestions(
			'org-new',
			db as unknown as Parameters<typeof seedDefaultQuestions>[1],
		);

		expect(copied).toBe(0);
		expect(create).not.toHaveBeenCalled();
	});
});
